In [2]:
import numpy as np
import pandas as pd

In [9]:
#Create 3*3 matrix
A = np.arange(21,30)
print(A)
A=A.reshape(3,3)
print(A)

[21 22 23 24 25 26 27 28 29]
[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [11]:
#Transpose
A.transpose()

array([[21, 24, 27],
       [22, 25, 28],
       [23, 26, 29]])

In [12]:
B = np.arange(31,40).reshape(3,3)
B

array([[31, 32, 33],
       [34, 35, 36],
       [37, 38, 39]])

In [14]:
AB = A.dot(B)
AB

array([[2250, 2316, 2382],
       [2556, 2631, 2706],
       [2862, 2946, 3030]])

In [16]:
BA = B.dot(A)
BA

array([[2310, 2406, 2502],
       [2526, 2631, 2736],
       [2742, 2856, 2970]])

In [19]:
C = np.arange(41,50).reshape(3,3)
C

array([[41, 42, 43],
       [44, 45, 46],
       [47, 48, 49]])

In [21]:
ABC = A.dot(B).dot(C)
ABC

array([[306108, 313056, 320004],
       [347742, 355635, 363528],
       [389376, 398214, 407052]])

## Determinant

In [24]:
matrixarr= np.arange(100,116).reshape(4,4)
matrixarr

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115]])

In [25]:
np.linalg.det(matrixarr)

-2.958228394578808e-31

## Inverse

In [26]:
np.linalg.inv(matrixarr)

array([[ 1.07228563e+14, -1.34035703e+14, -5.36142813e+13,
         8.04214219e+13],
       [-1.68134386e+17,  3.36268772e+17, -1.68134386e+17,
         1.22857143e+01],
       [ 3.35947086e+17, -6.72135437e+17,  3.36429615e+17,
        -2.41264266e+14],
       [-1.67919929e+17,  3.36000701e+17, -1.68241615e+17,
         1.60842844e+14]])